### PR TITLE
Using json-bigint instead of native JSON to fix long integer id's.

### PR DESCRIPTION
**Pull request by jbisson**
This is to address this specific issue: https://github.com/node-strava/node-strava-v3/issues/125

### CODE REVIEW

**Comment by markstos** [comment]
Thanks. Can you say more about this change works in testing? Is completely backwards compatible? Does it convert these big numbers into strings?

What can users of this module expect when they upgrade to a version with this change?

**Comment by jbisson** [comment]
It should be backward compatible yes. The difference is that long ID's will be converted to bigInt class (which support long ID) instead of native javascript integer and their toString() when using it will spit out the proper long integer string representative.

Basically, this change replace the JSON.parse() by the JSONbig.parse() function.

**Review by markstos — APPROVED** [review]

**Comment by markstos** [comment]
I'll try to get this released this week. Did you see the issue affecting more than Segment Effort IDs in the wild?

**Comment by jbisson** [comment]
I did not see anything else other than Segment Effort ID's at this point of time but anything that would be using long ID's will have the same issue.

**Pull request merged**
