### PR TITLE
Fixed editable athlete properties

### PR DESCRIPTION
**Pull request by ThaYoung1**
city, state, country and sex are not editable 
weight and ftp are editable

(see https://developers.strava.com/docs/oauth-updates/).

### CODE REVIEW

**Comment by markstos** [comment]
Thanks for this, but the URL you linked to doesn't  appear to document the change you are describing. I found the related page here, which only documents `weight` as a valid field to update.

How did you confirm that `ftp` was editable? 

https://developers.strava.com/docs/reference/#api-Athletes-updateLoggedInAthlete

**Comment by ThaYoung1** [comment]
Hi Markstos,

I found out by reading the changelog on https://developers.strava.com/docs/oauth-updates/.

It seems to be the case that not all Strava documentation (swagger,  https://developers.strava.com/docs/reference/ and the oauth updates) on the API are in-sync at the moment. 

Kind regards,

ThaYoung1

**Comment by markstos** [comment]
Considering that two different sets of documentation disagree, how do you know which is accurate? Did you test editing the FTP using the API?

I asked Strava to fix their documentation to make it consitent: https://groups.google.com/g/strava-api/c/d4Y8579p6kA

**Comment by ThaYoung1** [comment]
I created a Strava App for smart home platform Homey (see https://homey.app/nl-nl/app/com.thayoung1.strava/Strava/).

One of the features is that it can update the Athlete FTP setting. I can confirm that it works by using the App action card.

**Review by markstos — APPROVED** [review]

**Pull request merged**
